### ISSUE TITLE
Restart immediately when hp<=0

### ISSUE THREAD

**Issue by smkw33d** [nathan78906/steam-salien-cheat#20]
1 tick=2500 exp

**Comment by nathan78906** [comment]
OP wants me to check the result of the boss output and re-join when your player's HP is <=0. Currently the script will try and submit the score 3 times (and fail), then restart. This wastes ~15 seconds of xp gain. The reason why I didn't add this is because I made inputting STEAMID optional. 

I'll look into the early restart for people who've inputted the STEAMID.

**Comment by nathan78906** [comment]
If anyone would like to test, use the `boss-auto-restart` branch. I tried running it on 2 accounts for the latest boss but didnt die on any of them.

**Comment by NotJ3st3r** [comment]
I've tried it on the latest boss and it worked fine for me (with SteamID). When you die the script tries to recieve the bosses health and failes like 5 times. Afterwards it reconnects through the planet and zone selector.

**Comment by nathan78906** [comment]
Seems like it worked

![image](https://user-images.githubusercontent.com/24365131/42189502-79bc6012-7e26-11e8-9e81-d07c18fddd26.png)
